# Generated by Django 6.0 on 2025-12-14 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0003_alter_email_attachment_alter_email_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, unique=True)),
                ('opened', models.BooleanField(default=False, null=True)),
                ('clicked', models.BooleanField(default=False, null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Email.email')),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Email.subscriber')),
            ],
        ),
    ]
