# Generated by Django 6.0 on 2025-12-17 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0005_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtracking',
            name='clicked',
        ),
        migrations.RemoveField(
            model_name='emailtracking',
            name='opened',
        ),
        migrations.AddField(
            model_name='emailtracking',
            name='clicked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailtracking',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sent',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Email.email'),
        ),
    ]
