# Generated by Django 6.0 on 2025-12-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_entry', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('employee_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=200)),
                ('salary', models.IntegerField()),
                ('retirement', models.BooleanField()),
                ('other_benefits', models.BooleanField()),
                ('total_benefits', models.BooleanField()),
                ('total_compensation', models.BooleanField()),
            ],
        ),
    ]
