# Generated by Django 5.2.11 on 2026-03-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_entry', '0002_alter_customuser_id_alter_dailyusage_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='error_logs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='history',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('retrying', 'Retrying'), ('success', 'Success'), ('failed', 'Failed')], default='success', max_length=10),
        ),
        migrations.DeleteModel(
            name='ImportSession',
        ),
    ]
