# Generated by Django 6.0 on 2025-12-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_entry', '0003_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.BooleanField(),
        ),
    ]
